/*
 * JSP generated by Resin-3.0.17 (built Thu, 22 Dec 2005 12:11:34 PST)
 */

package _jsp._decorators;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _main_0decorator__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.Application _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = com.caucho.jsp.QJspFactory.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true);
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html;charset=UTF-8");
    request.setCharacterEncoding("UTF-8");
    com.opensymphony.module.sitemesh.taglib.decorator.TitleTag _jsp_TitleTag_0 = null;
    com.opensymphony.module.sitemesh.taglib.decorator.HeadTag _jsp_HeadTag_1 = null;
    com.opensymphony.module.sitemesh.taglib.decorator.BodyTag _jsp_BodyTag_2 = null;
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      if (_jsp_TitleTag_0 == null) {
        _jsp_TitleTag_0 = new com.opensymphony.module.sitemesh.taglib.decorator.TitleTag();
        _jsp_TitleTag_0.setPageContext(pageContext);
        _jsp_TitleTag_0.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_TitleTag_0.doEndTag();
      out.write(_jsp_string1, 0, _jsp_string1.length);
      if (_jsp_HeadTag_1 == null) {
        _jsp_HeadTag_1 = new com.opensymphony.module.sitemesh.taglib.decorator.HeadTag();
        _jsp_HeadTag_1.setPageContext(pageContext);
        _jsp_HeadTag_1.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_HeadTag_1.doEndTag();
      out.write(_jsp_string2, 0, _jsp_string2.length);
      if (_jsp_BodyTag_2 == null) {
        _jsp_BodyTag_2 = new com.opensymphony.module.sitemesh.taglib.decorator.BodyTag();
        _jsp_BodyTag_2.setPageContext(pageContext);
        _jsp_BodyTag_2.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_BodyTag_2.doEndTag();
      out.write(_jsp_string3, 0, _jsp_string3.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      if (_jsp_TitleTag_0 != null)
        _jsp_TitleTag_0.release();
      if (_jsp_HeadTag_1 != null)
        _jsp_HeadTag_1.release();
      if (_jsp_BodyTag_2 != null)
        _jsp_BodyTag_2.release();
      com.caucho.jsp.QJspFactory.freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.make.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.util.CauchoSystem.getVersionId() != -4988191405718430679L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.make.Dependency depend;
      depend = (com.caucho.make.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("decorators/main_decorator.jsp"), -7398249299187631049L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/sitemesh-decorator.tld"), -6903750038067261476L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, new com.caucho.make.ClassDependency(com.opensymphony.module.sitemesh.taglib.decorator.TitleTag.class, 322528183087701306L));
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, new com.caucho.make.ClassDependency(com.opensymphony.module.sitemesh.taglib.decorator.HeadTag.class, 239536800145831584L));
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, new com.caucho.make.ClassDependency(com.opensymphony.module.sitemesh.taglib.decorator.BodyTag.class, 4575265640836712976L));
  }

  private final static char []_jsp_string0;
  private final static char []_jsp_string1;
  private final static char []_jsp_string2;
  private final static char []_jsp_string3;
  static {
    _jsp_string0 = "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\"\n\"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\n<html xmlns=\"http://www.w3.org/1999/xhtml\" lang=\"en\" xml:lang=\"en\">\n  <head><title>This is decorator ".toCharArray();
    _jsp_string1 = "</title>\n      <link rel=\"stylesheet\" href=\"/styles/main.css\" type=\"text/css\" />\n      ".toCharArray();
    _jsp_string2 = "\n  </head>\n  <body>\n  <div id=\"maincontainer\">\n\n      <div id=\"container\">\n          ".toCharArray();
    _jsp_string3 = "\n      </div>\n\n  </div>\n\n\n  </body>\n</html>".toCharArray();
  }
}
