/*
 * JSP generated by Resin-3.0.17 (built Thu, 22 Dec 2005 12:11:34 PST)
 */

package _jsp._templates;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _registrationpage__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.Application _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = com.caucho.jsp.QJspFactory.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true);
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html;charset=UTF-8");
    request.setCharacterEncoding("UTF-8");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      
            if ( request.getAttribute("message") != null && ! request.getAttribute("message").equals("")){
                
      out.write(_jsp_string1, 0, _jsp_string1.length);
      out.print((request.getAttribute("message")));
      out.write(_jsp_string2, 0, _jsp_string2.length);
      
            }
        
      
        if ( request.getAttribute("success") == null ){
        
      out.write(_jsp_string3, 0, _jsp_string3.length);
      
            }
        
      out.write(_jsp_string4, 0, _jsp_string4.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      com.caucho.jsp.QJspFactory.freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.make.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.util.CauchoSystem.getVersionId() != -4988191405718430679L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.make.Dependency depend;
      depend = (com.caucho.make.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("templates/RegistrationPage.jsp"), -9047426710345055905L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  private final static char []_jsp_string2;
  private final static char []_jsp_string4;
  private final static char []_jsp_string1;
  private final static char []_jsp_string0;
  private final static char []_jsp_string3;
  static {
    _jsp_string2 = "\n        </div>\n        ".toCharArray();
    _jsp_string4 = "\n\n    </div>\n\n\n  </body>\n</html>".toCharArray();
    _jsp_string1 = "\n        <div id=\"errorbox\">\n            ".toCharArray();
    _jsp_string0 = "\n\n<html>\n  <head><title>Registration</title>\n    <link rel=\"stylesheet\" href=\"/styles/registration.css\" type=\"text/css\" />\n  </head>\n  <body>\n    <div id=\"registrationbox\">\n        <span class=\"title\">Remember, it's imperative that all fields are filled in correctly</span><br />\n        ".toCharArray();
    _jsp_string3 = "\n        <form action=\"/register\" method=\"post\">\n            <table id=\"regtable\" cellpadding=\"0\" cellspacing=\"0\">\n                <tr>\n                    <td>Username</td><td><input type=\"text\" name=\"username\" /></td>\n                </tr>\n                <tr>\n                    <td>Password</td><td><input type=\"password\" name=\"password\" /></td>\n                </tr>\n                <tr>\n                    <td>Verify password</td><td><input type=\"password\" name=\"password2\" /></td>\n                </tr>\n                <tr>\n                    <td>Email</td><td><input type=\"text\" name=\"email\" /></td>\n                </tr>\n                <tr>\n                    <td colspan=\"2\"><input type=\"submit\" name=\"submit\" value=\"Register\" /></td>\n                </tr>\n            </table>\n        </form>\n        ".toCharArray();
  }
}
